# Generated by Django 2.2 on 2019-04-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Тип комнаты')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Цена комнаты')),
            ],
            options={
                'verbose_name': 'Тип комнаты',
                'verbose_name_plural': 'Типы комнат',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_room', models.IntegerField(blank=True, null=True, verbose_name='Номер комнаты')),
                ('type_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsm.TypeRoom', verbose_name='Тип комнаты')),
            ],
            options={
                'verbose_name': 'Номер комнаты',
                'verbose_name_plural': 'Номера комнат',
            },
        ),
    ]
