# Generated by Django 2.2 on 2019-04-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Национальность')),
            ],
            options={
                'verbose_name': 'Национальность',
                'verbose_name_plural': 'Национальности',
            },
        ),
        migrations.CreateModel(
            name='SourceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Источник бронирования')),
            ],
            options={
                'verbose_name': 'Источник брони',
                'verbose_name_plural': 'Источники брони',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Что сделать')),
                ('info', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TypePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='номер')),
                ('visa_type', models.CharField(max_length=50, verbose_name='тип')),
                ('given_date', models.DateField(verbose_name='Дата выдачи')),
                ('expire_date', models.DateField(verbose_name='Дата окончания срока')),
            ],
            options={
                'verbose_name': 'Виза',
                'verbose_name_plural': 'Визы',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True, verbose_name='Ф.И.О')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер паспорта')),
                ('given_date', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('expire_date', models.DateField(verbose_name='Дата окончания срока паспорта')),
                ('give_organization', models.CharField(max_length=100, verbose_name='Кем выдано')),
                ('place_of_living', models.CharField(max_length=100, verbose_name='Место проживания')),
                ('citeznship', models.CharField(max_length=50, verbose_name='Гражданство')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsm.Nationality', verbose_name='Национальность')),
                ('place_of_birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsm.City', verbose_name='Место рождение: город')),
                ('visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.Visa', verbose_name='VISA')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_arrival', models.IntegerField(default=0, verbose_name='Дата заезда в Timestamp')),
                ('date_of_departure', models.IntegerField(default=0, verbose_name='Дата выезда в Timestamp')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена за ночь')),
                ('price_for_all_time', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена за неделю')),
                ('number_source_booking', models.CharField(blank=True, max_length=50, verbose_name='Номер брони источника')),
                ('status_booking', models.IntegerField(choices=[(0, 'Пусто'), (-1, 'Бронь без оплаты'), (1, 'Бронь с предоплатой'), (-2, 'Размещение гостя с долгом'), (2, 'Размещение гостя с оплатой'), (-3, 'Выселенное размещение'), (3, 'Резерв'), (4, 'Гости сегодня выезжают'), (-4, 'Блокировка номера')], default=0, verbose_name='Статус брони')),
                ('admin_comment', models.TextField(verbose_name='Комментарий администратора')),
                ('customer_wishes', models.TextField(verbose_name='Пожелания гостя')),
                ('guest', models.ManyToManyField(blank=True, null=True, to='hsm.Guest', verbose_name='Проживающие гости')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsm.Rooms', verbose_name='Номер остановки')),
                ('source_of_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsm.SourceBooking', verbose_name='Источник бронирования')),
                ('type_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsm.TypePayment', verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
