# Generated by Django 2.2 on 2019-04-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0002_booking_city_guest_nationality_sourcebooking_tag_task_typepayment_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.Task', verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_wishes',
            field=models.TextField(blank=True, verbose_name='Пожелания гостя'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ManyToManyField(blank=True, to='hsm.Guest', verbose_name='Проживающие гости'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.Rooms', verbose_name='Номер остановки'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source_of_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.SourceBooking', verbose_name='Источник бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.TypePayment', verbose_name='Тип оплаты'),
        ),
    ]
