# Generated by Django 2.2 on 2019-04-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0003_auto_20190409_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alarm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Когда выполнить'),
        ),
    ]
