# Generated by Django 2.2 on 2019-04-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0004_task_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citeznship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Гражданство')),
            ],
            options={
                'verbose_name': 'Гражданство',
                'verbose_name_plural': 'Гражданства',
            },
        ),
        migrations.AlterField(
            model_name='guest',
            name='citeznship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.Citeznship', verbose_name='Гражданство'),
        ),
    ]
