# Generated by Django 2.2 on 2019-04-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0006_auto_20190410_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Что сделать'),
        ),
    ]
