# Generated by Django 2.2 on 2019-04-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0007_auto_20190410_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='expire_date',
            field=models.CharField(max_length=30, verbose_name='Дата окончания срока паспорта'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='given_date',
            field=models.CharField(max_length=30, verbose_name='Дата выдачи паспорта'),
        ),
    ]
