# Generated by Django 2.2 on 2019-04-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0008_auto_20190413_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='expire_date',
            field=models.CharField(max_length=30, verbose_name='Дата окончания срока'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='given_date',
            field=models.CharField(max_length=30, verbose_name='Дата выдачи'),
        ),
    ]
