# Generated by Django 2.2 on 2019-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0009_auto_20190413_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_of_birth',
            field=models.CharField(max_length=50, verbose_name='Дата рождения'),
        ),
    ]
