# Generated by Django 2.2 on 2019-04-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0010_auto_20190413_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='expire_date',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дата окончания срока паспорта'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='give_organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кем выдано'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='given_date',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.Nationality', verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.City', verbose_name='Место рождение: город'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='place_of_living',
            field=models.CharField(blank=True, max_length=100, verbose_name='Место проживания'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Серийный номер паспорта'),
        ),
    ]
