# Generated by Django 2.2 on 2019-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0011_auto_20190413_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typepayment',
            options={'verbose_name': 'Тип оплаты', 'verbose_name_plural': 'Типы оплат'},
        ),
        migrations.AlterField(
            model_name='rooms',
            name='number_room',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер комнаты'),
        ),
    ]
