# Generated by Django 2.2 on 2019-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0012_auto_20190414_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_of_arrival_time',
            field=models.CharField(blank=True, max_length=10, verbose_name='Время заезда'),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_of_departure_time',
            field=models.CharField(blank=True, max_length=10, verbose_name='Время выезда'),
        ),
    ]
