# Generated by Django 2.2 on 2019-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0014_datetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время заезда'),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выезда'),
        ),
    ]
