# Generated by Django 2.2 on 2019-04-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0020_auto_20190418_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_of_arrival',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_of_arrival_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_of_departure',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_of_departure_time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_for_all_time',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена за всё время'),
        ),
    ]
