# Generated by Django 2.2 on 2019-04-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0021_auto_20190419_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='kpp_date_arrival',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дата заезда КПП'),
        ),
    ]
