# Generated by Django 2.2 on 2019-04-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0022_auto_20190419_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Суток'),
        ),
        migrations.AddField(
            model_name='booking',
            name='left_to_pay',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Осталось оплатить'),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_for_all_time',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена за всё время'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена за ночь'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type_payment',
            field=models.IntegerField(choices=[(0, 'Не известно'), (1, 'Наличка'), (2, 'Пластик'), (3, 'Перечисление')], default=0, verbose_name='Тип оплаты'),
        ),
    ]
