# Generated by Django 2.2 on 2019-04-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0025_booking_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='passport',
            field=models.BooleanField(default=True, verbose_name='Паспорт в наличии'),
        ),
    ]
