# Generated by Django 2.2 on 2019-04-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0027_auto_20190420_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Сумма')),
                ('type_payment', models.IntegerField(choices=[(0, 'Не известно'), (1, 'Наличка'), (2, 'Пластик'), (3, 'Перечисление'), (4, 'В долларах')], default=0, verbose_name='Тип оплаты')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsm.Booking', verbose_name='ID брони')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Тип оплаты',
            },
        ),
    ]
