# Generated by Django 2.2 on 2019-04-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0028_pricebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='type_payment',
        ),
    ]
