# Generated by Django 2.2 on 2019-04-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0030_auto_20190424_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.Booking', verbose_name='ID брони')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.Services', verbose_name='Доп. услуга')),
            ],
            options={
                'verbose_name': 'Доп. услуга',
                'verbose_name_plural': 'Доп. услуги',
            },
        ),
        migrations.CreateModel(
            name='OwnServicesBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Услуга')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена')),
                ('type_payment', models.IntegerField(choices=[(0, 'Не известно'), (1, 'Наличка'), (2, 'Пластик'), (3, 'Перечисление'), (4, 'В долларах')], default=0, verbose_name='Тип оплаты')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.Booking', verbose_name='ID брони')),
            ],
            options={
                'verbose_name': 'Доп. платёж',
                'verbose_name_plural': 'Доп. платежи',
            },
        ),
    ]
