# Generated by Django 2.2 on 2019-04-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0031_ownservicesbooking_servicesbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownservicesbooking',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownservicesbooking', to='hsm.Booking', verbose_name='ID брони'),
        ),
        migrations.AlterField(
            model_name='servicesbooking',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicesbooking', to='hsm.Booking', verbose_name='ID брони'),
        ),
    ]
