# Generated by Django 2.2 on 2019-04-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0032_auto_20190424_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesbooking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicesb', to='hsm.Services', verbose_name='Доп. услуга'),
        ),
    ]
