# Generated by Django 2.2 on 2019-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0034_auto_20190424_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='days',
            field=models.FloatField(blank=True, null=True, verbose_name='Суток'),
        ),
    ]
