# Generated by Django 2.2 on 2019-04-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0035_auto_20190426_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesbooking',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='servicesbooking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_bez_nal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма - перечисление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_nal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма - налом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_terminal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма - терминал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_usd',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма - в долларах'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PriceBooking',
        ),
        migrations.DeleteModel(
            name='ServicesBooking',
        ),
    ]
