# Generated by Django 2.2 on 2019-04-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0036_auto_20190426_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_usd',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма - в долларах'),
        ),
    ]
