# Generated by Django 2.2 on 2019-04-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0037_auto_20190426_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_bez_nal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма - перечисление'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_nal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма - налом'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_terminal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма - терминал'),
        ),
    ]
